INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('João Silva', '12345678901', '1985-02-15', 'FLAMMABLE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Maria Oliveira', '23456789012', '1990-07-21', 'PERISHABLE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Carlos Pereira', '34567890123', '1982-11-03', 'TOXIC', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Ana Costa', '45678901234', '1995-05-17', 'FRAGILE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Rafael Souza', '56789012345', '1988-09-29', 'HIGH_VALUE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Larissa Martins', '67890123456', '1992-03-12', 'EXPLOSIVE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Paulo Gomes', '78901234567', '1987-12-08', 'CORROSIVE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Juliana Rocha', '89012345678', '1991-06-25', 'RADIOACTIVE', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Bruno Lima', '90123456789', '1983-10-14', 'OVERSIZED', 'AVAILABLE');
INSERT INTO Driver (name, cpf, birth_date, specification, situation) VALUES ('Fernanda Alves', '01234567890', '1994-01-30', 'FRAGILE', 'AVAILABLE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('ABC1234', 'Volvo FH', 12000, 'AVAILABLE', 'LOW', 'FLAMMABLE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('DEF5678', 'Mercedes Actros', 15000, 'AVAILABLE', 'MEDIUM', 'PERISHABLE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('GHI9012', 'Scania R500', 10000, 'AVAILABLE', 'HIGH', 'TOXIC');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('JKL3456', 'MAN TGX', 13000, 'AVAILABLE', 'LOW', 'FRAGILE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('MNO7890', 'Iveco Stralis', 14000, 'AVAILABLE', 'MEDIUM', 'HIGH_VALUE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('PQR1234', 'DAF XF', 11000, 'AVAILABLE', 'LOW', 'EXPLOSIVE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('STU5678', 'Renault T', 12500, 'AVAILABLE', 'HIGH', 'CORROSIVE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('VWX9012', 'Volvo FM', 13500, 'AVAILABLE', 'MEDIUM', 'RADIOACTIVE');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('YZA3456', 'Scania P340', 12000, 'AVAILABLE', 'LOW', 'OVERSIZED');
INSERT INTO Vehicle (plate, model, capacity, availability, maintenance, specification) VALUES ('BCD7890', 'Mercedes Axor', 14500, 'AVAILABLE', 'MEDIUM', 'FRAGILE');
